### ISSUE TITLE
defendant name is adding additional whitespace

### ISSUE THREAD

**Issue by jsugarman** [ministryofjustice/laa-court-data-adaptor#395]
**Expected behavior** 
When we call a defendants name attribute it is expected to be single space delimited
e.g. `Jammy Dodger`

**Actual behaviour**
The name is double spaced delimited
e.g. `Jammy  Dodger`

**Cause**

https://github.com/ministryofjustice/laa-court-data-adaptor/blob/master/app/models/defendant.rb#L13
```
[first_name, middle_name, last_name].compact.join(" ")
```
when middle name is an empty string it results in an extra whitespace.
```
['Jammy', '', 'Dodger'].compact.join(" ")
=> "Jammy  Dodger"
```

**Impact** 
Just noticed that VCD searching by name does not work as a result unless you put two spaces between first and last name you are search for

**Fix**
use  rails's `squish` or ruby's `squeeze(' ')`
```
['Jammy', '', 'Dodger'].join(' ').squish
 => "Jammy Dodger"

# ALSO WORKS WITH NILS
['Jammy', nil, 'Dodger'].join(' ').squish
 => "Jammy Dodger"
```

**Comment by laurentqro** [comment]
Fixed in https://github.com/ministryofjustice/laa-court-data-adaptor/pull/397.
