### ISSUE TITLE
Test hyper-schema

### ISSUE THREAD

**Issue by jsugarman** [ministryofjustice/laa-court-data-adaptor#55]
The available schema testing gems include
[json-schema](https://github.com/ruby-json-schema/json-schema) - does not support `hyper-schema`
[json_schemer](https://github.com/davishmcclurg/json_schemer) - does not support `hyper-schema`

[json_schema](https://github.com/brandur/json_schema) - supports `v4 hyper-schema` but raises an error against the current `schema.json`

```
schema_data = JSON.parse(File.read("schema.json"))
schema = JsonSchema.parse!(schema_data)
=> JsonSchema::AggregateError
```
I am not sure if this is a problem or not but should probably be looked into if we are aiming for [jsonapi](https://jsonapi.org) compliant responses

**Comment by archferns** [comment]
Fixed via #56
